### ISSUE TITLE
ToDo task list view - backend

### ISSUE THREAD

**Issue by mialsy** [ios-project-usfca-2021sp/breathe#34]
- [x] set check box to have different image displayed
- [x] get todo task from parse
- [x] display tasks on todo task list view screen
